// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/library.dart';
import 'api/references.dart';
import 'api/typeset.dart';
import 'api/user.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DictLayoutView dco_decode_box_autoadd_dict_layout_view(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  ChapterLayoutView dco_decode_chapter_layout_view(dynamic raw);

  @protected
  ChapterRefView dco_decode_chapter_ref_view(dynamic raw);

  @protected
  ChapterView dco_decode_chapter_view(dynamic raw);

  @protected
  CommentLayoutView dco_decode_comment_layout_view(dynamic raw);

  @protected
  CommentView dco_decode_comment_view(dynamic raw);

  @protected
  ConcordanceResult dco_decode_concordance_result(dynamic raw);

  @protected
  DictHitView dco_decode_dict_hit_view(dynamic raw);

  @protected
  DictLayoutView dco_decode_dict_layout_view(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LineView dco_decode_line_view(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<ChapterRefView> dco_decode_list_chapter_ref_view(dynamic raw);

  @protected
  List<CommentLayoutView> dco_decode_list_comment_layout_view(dynamic raw);

  @protected
  List<CommentView> dco_decode_list_comment_view(dynamic raw);

  @protected
  List<DictHitView> dco_decode_list_dict_hit_view(dynamic raw);

  @protected
  List<LineView> dco_decode_list_line_view(dynamic raw);

  @protected
  List<ModuleView> dco_decode_list_module_view(dynamic raw);

  @protected
  List<NoteRefView> dco_decode_list_note_ref_view(dynamic raw);

  @protected
  List<NoteView> dco_decode_list_note_view(dynamic raw);

  @protected
  List<OccurrenceView> dco_decode_list_occurrence_view(dynamic raw);

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RunView> dco_decode_list_run_view(dynamic raw);

  @protected
  List<VerseView> dco_decode_list_verse_view(dynamic raw);

  @protected
  ModuleView dco_decode_module_view(dynamic raw);

  @protected
  NoteRefView dco_decode_note_ref_view(dynamic raw);

  @protected
  NoteView dco_decode_note_view(dynamic raw);

  @protected
  OccurrenceView dco_decode_occurrence_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DictLayoutView? dco_decode_opt_box_autoadd_dict_layout_view(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  ParseOutcome dco_decode_parse_outcome(dynamic raw);

  @protected
  RunView dco_decode_run_view(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VerseView dco_decode_verse_view(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DictLayoutView sse_decode_box_autoadd_dict_layout_view(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ChapterLayoutView sse_decode_chapter_layout_view(
    SseDeserializer deserializer,
  );

  @protected
  ChapterRefView sse_decode_chapter_ref_view(SseDeserializer deserializer);

  @protected
  ChapterView sse_decode_chapter_view(SseDeserializer deserializer);

  @protected
  CommentLayoutView sse_decode_comment_layout_view(
    SseDeserializer deserializer,
  );

  @protected
  CommentView sse_decode_comment_view(SseDeserializer deserializer);

  @protected
  ConcordanceResult sse_decode_concordance_result(SseDeserializer deserializer);

  @protected
  DictHitView sse_decode_dict_hit_view(SseDeserializer deserializer);

  @protected
  DictLayoutView sse_decode_dict_layout_view(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LineView sse_decode_line_view(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<ChapterRefView> sse_decode_list_chapter_ref_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommentLayoutView> sse_decode_list_comment_layout_view(
    SseDeserializer deserializer,
  );

  @protected
  List<CommentView> sse_decode_list_comment_view(SseDeserializer deserializer);

  @protected
  List<DictHitView> sse_decode_list_dict_hit_view(SseDeserializer deserializer);

  @protected
  List<LineView> sse_decode_list_line_view(SseDeserializer deserializer);

  @protected
  List<ModuleView> sse_decode_list_module_view(SseDeserializer deserializer);

  @protected
  List<NoteRefView> sse_decode_list_note_ref_view(SseDeserializer deserializer);

  @protected
  List<NoteView> sse_decode_list_note_view(SseDeserializer deserializer);

  @protected
  List<OccurrenceView> sse_decode_list_occurrence_view(
    SseDeserializer deserializer,
  );

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RunView> sse_decode_list_run_view(SseDeserializer deserializer);

  @protected
  List<VerseView> sse_decode_list_verse_view(SseDeserializer deserializer);

  @protected
  ModuleView sse_decode_module_view(SseDeserializer deserializer);

  @protected
  NoteRefView sse_decode_note_ref_view(SseDeserializer deserializer);

  @protected
  NoteView sse_decode_note_view(SseDeserializer deserializer);

  @protected
  OccurrenceView sse_decode_occurrence_view(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DictLayoutView? sse_decode_opt_box_autoadd_dict_layout_view(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ParseOutcome sse_decode_parse_outcome(SseDeserializer deserializer);

  @protected
  RunView sse_decode_run_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VerseView sse_decode_verse_view(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_dict_layout_view(
    DictLayoutView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_layout_view(
    ChapterLayoutView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter_ref_view(
    ChapterRefView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter_view(ChapterView self, SseSerializer serializer);

  @protected
  void sse_encode_comment_layout_view(
    CommentLayoutView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_comment_view(CommentView self, SseSerializer serializer);

  @protected
  void sse_encode_concordance_result(
    ConcordanceResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dict_hit_view(DictHitView self, SseSerializer serializer);

  @protected
  void sse_encode_dict_layout_view(
    DictLayoutView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_line_view(LineView self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_ref_view(
    List<ChapterRefView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_comment_layout_view(
    List<CommentLayoutView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_comment_view(
    List<CommentView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dict_hit_view(
    List<DictHitView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_line_view(List<LineView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_module_view(
    List<ModuleView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_ref_view(
    List<NoteRefView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_view(List<NoteView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_occurrence_view(
    List<OccurrenceView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_run_view(List<RunView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_verse_view(
    List<VerseView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_module_view(ModuleView self, SseSerializer serializer);

  @protected
  void sse_encode_note_ref_view(NoteRefView self, SseSerializer serializer);

  @protected
  void sse_encode_note_view(NoteView self, SseSerializer serializer);

  @protected
  void sse_encode_occurrence_view(
    OccurrenceView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_dict_layout_view(
    DictLayoutView? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_parse_outcome(ParseOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_run_view(RunView self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verse_view(VerseView self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
