// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/library.dart';
import 'api/references.dart';
import 'api/typeset.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  ChapterLayoutView dco_decode_chapter_layout_view(dynamic raw);

  @protected
  ChapterRefView dco_decode_chapter_ref_view(dynamic raw);

  @protected
  ChapterView dco_decode_chapter_view(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LineView dco_decode_line_view(dynamic raw);

  @protected
  List<ChapterRefView> dco_decode_list_chapter_ref_view(dynamic raw);

  @protected
  List<LineView> dco_decode_list_line_view(dynamic raw);

  @protected
  List<ModuleView> dco_decode_list_module_view(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RunView> dco_decode_list_run_view(dynamic raw);

  @protected
  List<VerseView> dco_decode_list_verse_view(dynamic raw);

  @protected
  ModuleView dco_decode_module_view(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ParseOutcome dco_decode_parse_outcome(dynamic raw);

  @protected
  RunView dco_decode_run_view(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  VerseView dco_decode_verse_view(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  ChapterLayoutView sse_decode_chapter_layout_view(
    SseDeserializer deserializer,
  );

  @protected
  ChapterRefView sse_decode_chapter_ref_view(SseDeserializer deserializer);

  @protected
  ChapterView sse_decode_chapter_view(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LineView sse_decode_line_view(SseDeserializer deserializer);

  @protected
  List<ChapterRefView> sse_decode_list_chapter_ref_view(
    SseDeserializer deserializer,
  );

  @protected
  List<LineView> sse_decode_list_line_view(SseDeserializer deserializer);

  @protected
  List<ModuleView> sse_decode_list_module_view(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RunView> sse_decode_list_run_view(SseDeserializer deserializer);

  @protected
  List<VerseView> sse_decode_list_verse_view(SseDeserializer deserializer);

  @protected
  ModuleView sse_decode_module_view(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ParseOutcome sse_decode_parse_outcome(SseDeserializer deserializer);

  @protected
  RunView sse_decode_run_view(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  VerseView sse_decode_verse_view(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_chapter_layout_view(
    ChapterLayoutView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter_ref_view(
    ChapterRefView self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_chapter_view(ChapterView self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_line_view(LineView self, SseSerializer serializer);

  @protected
  void sse_encode_list_chapter_ref_view(
    List<ChapterRefView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_line_view(List<LineView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_module_view(
    List<ModuleView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_run_view(List<RunView> self, SseSerializer serializer);

  @protected
  void sse_encode_list_verse_view(
    List<VerseView> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_module_view(ModuleView self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_parse_outcome(ParseOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_run_view(RunView self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_verse_view(VerseView self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
