// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/library.dart';
import 'api/references.dart';
import 'api/typeset.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiReferencesInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -458430742;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_gramma',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  ChapterView crateApiLibraryChapter({
    required String moduleCode,
    required String reference,
  });

  List<VerseView> crateApiLibraryChapterVerses({
    required String moduleCode,
    required String bookOsis,
    required int chapter,
  });

  List<ChapterRefView> crateApiLibraryContents({required String moduleCode});

  Future<ModuleView> crateApiLibraryImportOsisFile({required String path});

  Future<void> crateApiReferencesInitApp();

  void crateApiTypesetInitTypesetting({required List<int> fontData});

  Future<ChapterLayoutView> crateApiTypesetLayoutChapter({
    required String moduleCode,
    required String bookOsis,
    required int chapter,
  });

  Future<Uint32List> crateApiTypesetModuleLineCounts({
    required String moduleCode,
  });

  List<ModuleView> crateApiLibraryModules();

  void crateApiLibraryOpenLibrary({required String path});

  ParseOutcome crateApiReferencesParseReference({required String input});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ChapterView crateApiLibraryChapter({
    required String moduleCode,
    required String reference,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleCode, serializer);
          sse_encode_String(reference, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryChapterConstMeta,
        argValues: [moduleCode, reference],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryChapterConstMeta => const TaskConstMeta(
    debugName: "chapter",
    argNames: ["moduleCode", "reference"],
  );

  @override
  List<VerseView> crateApiLibraryChapterVerses({
    required String moduleCode,
    required String bookOsis,
    required int chapter,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleCode, serializer);
          sse_encode_String(bookOsis, serializer);
          sse_encode_u_16(chapter, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_verse_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryChapterVersesConstMeta,
        argValues: [moduleCode, bookOsis, chapter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryChapterVersesConstMeta =>
      const TaskConstMeta(
        debugName: "chapter_verses",
        argNames: ["moduleCode", "bookOsis", "chapter"],
      );

  @override
  List<ChapterRefView> crateApiLibraryContents({required String moduleCode}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleCode, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_chapter_ref_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryContentsConstMeta,
        argValues: [moduleCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryContentsConstMeta =>
      const TaskConstMeta(debugName: "contents", argNames: ["moduleCode"]);

  @override
  Future<ModuleView> crateApiLibraryImportOsisFile({required String path}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_module_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryImportOsisFileConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryImportOsisFileConstMeta =>
      const TaskConstMeta(debugName: "import_osis_file", argNames: ["path"]);

  @override
  Future<void> crateApiReferencesInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReferencesInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReferencesInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiTypesetInitTypesetting({required List<int> fontData}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(fontData, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTypesetInitTypesettingConstMeta,
        argValues: [fontData],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesetInitTypesettingConstMeta =>
      const TaskConstMeta(
        debugName: "init_typesetting",
        argNames: ["fontData"],
      );

  @override
  Future<ChapterLayoutView> crateApiTypesetLayoutChapter({
    required String moduleCode,
    required String bookOsis,
    required int chapter,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleCode, serializer);
          sse_encode_String(bookOsis, serializer);
          sse_encode_u_16(chapter, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chapter_layout_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTypesetLayoutChapterConstMeta,
        argValues: [moduleCode, bookOsis, chapter],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesetLayoutChapterConstMeta =>
      const TaskConstMeta(
        debugName: "layout_chapter",
        argNames: ["moduleCode", "bookOsis", "chapter"],
      );

  @override
  Future<Uint32List> crateApiTypesetModuleLineCounts({
    required String moduleCode,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(moduleCode, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_32_strict,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiTypesetModuleLineCountsConstMeta,
        argValues: [moduleCode],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiTypesetModuleLineCountsConstMeta =>
      const TaskConstMeta(
        debugName: "module_line_counts",
        argNames: ["moduleCode"],
      );

  @override
  List<ModuleView> crateApiLibraryModules() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_module_view,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryModulesConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryModulesConstMeta =>
      const TaskConstMeta(debugName: "modules", argNames: []);

  @override
  void crateApiLibraryOpenLibrary({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_AnyhowException,
        ),
        constMeta: kCrateApiLibraryOpenLibraryConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiLibraryOpenLibraryConstMeta =>
      const TaskConstMeta(debugName: "open_library", argNames: ["path"]);

  @override
  ParseOutcome crateApiReferencesParseReference({required String input}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(input, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parse_outcome,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiReferencesParseReferenceConstMeta,
        argValues: [input],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiReferencesParseReferenceConstMeta =>
      const TaskConstMeta(debugName: "parse_reference", argNames: ["input"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChapterLayoutView dco_decode_chapter_layout_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ChapterLayoutView(
      lines: dco_decode_list_line_view(arr[0]),
      unitsPerEm: dco_decode_u_16(arr[1]),
      measureUnits: dco_decode_i_64(arr[2]),
      numberScale: dco_decode_f_64(arr[3]),
      plainText: dco_decode_String(arr[4]),
    );
  }

  @protected
  ChapterRefView dco_decode_chapter_ref_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ChapterRefView(
      bookOsis: dco_decode_String(arr[0]),
      chapter: dco_decode_u_16(arr[1]),
      heading: dco_decode_String(arr[2]),
      textLength: dco_decode_i_64(arr[3]),
    );
  }

  @protected
  ChapterView dco_decode_chapter_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ChapterView(
      osis: dco_decode_String(arr[0]),
      verses: dco_decode_list_verse_view(arr[1]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  LineView dco_decode_line_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return LineView(runs: dco_decode_list_run_view(arr[0]));
  }

  @protected
  List<ChapterRefView> dco_decode_list_chapter_ref_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_chapter_ref_view).toList();
  }

  @protected
  List<LineView> dco_decode_list_line_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_line_view).toList();
  }

  @protected
  List<ModuleView> dco_decode_list_module_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_module_view).toList();
  }

  @protected
  Uint32List dco_decode_list_prim_u_32_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint32List;
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RunView> dco_decode_list_run_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_run_view).toList();
  }

  @protected
  List<VerseView> dco_decode_list_verse_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_verse_view).toList();
  }

  @protected
  ModuleView dco_decode_module_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ModuleView(
      code: dco_decode_String(arr[0]),
      title: dco_decode_String(arr[1]),
      language: dco_decode_String(arr[2]),
      verses: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ParseOutcome dco_decode_parse_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ParseOutcome(
      osis: dco_decode_opt_String(arr[0]),
      error: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  RunView dco_decode_run_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return RunView(
      text: dco_decode_String(arr[0]),
      x: dco_decode_f_64(arr[1]),
      width: dco_decode_f_64(arr[2]),
      verseNumber: dco_decode_bool(arr[3]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  VerseView dco_decode_verse_view(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return VerseView(
      verse: dco_decode_u_16(arr[0]),
      text: dco_decode_String(arr[1]),
    );
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChapterLayoutView sse_decode_chapter_layout_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_lines = sse_decode_list_line_view(deserializer);
    var var_unitsPerEm = sse_decode_u_16(deserializer);
    var var_measureUnits = sse_decode_i_64(deserializer);
    var var_numberScale = sse_decode_f_64(deserializer);
    var var_plainText = sse_decode_String(deserializer);
    return ChapterLayoutView(
      lines: var_lines,
      unitsPerEm: var_unitsPerEm,
      measureUnits: var_measureUnits,
      numberScale: var_numberScale,
      plainText: var_plainText,
    );
  }

  @protected
  ChapterRefView sse_decode_chapter_ref_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_bookOsis = sse_decode_String(deserializer);
    var var_chapter = sse_decode_u_16(deserializer);
    var var_heading = sse_decode_String(deserializer);
    var var_textLength = sse_decode_i_64(deserializer);
    return ChapterRefView(
      bookOsis: var_bookOsis,
      chapter: var_chapter,
      heading: var_heading,
      textLength: var_textLength,
    );
  }

  @protected
  ChapterView sse_decode_chapter_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_osis = sse_decode_String(deserializer);
    var var_verses = sse_decode_list_verse_view(deserializer);
    return ChapterView(osis: var_osis, verses: var_verses);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  LineView sse_decode_line_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_runs = sse_decode_list_run_view(deserializer);
    return LineView(runs: var_runs);
  }

  @protected
  List<ChapterRefView> sse_decode_list_chapter_ref_view(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ChapterRefView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_chapter_ref_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<LineView> sse_decode_list_line_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LineView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_line_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<ModuleView> sse_decode_list_module_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ModuleView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_module_view(deserializer));
    }
    return ans_;
  }

  @protected
  Uint32List sse_decode_list_prim_u_32_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint32List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RunView> sse_decode_list_run_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RunView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_run_view(deserializer));
    }
    return ans_;
  }

  @protected
  List<VerseView> sse_decode_list_verse_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VerseView>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_verse_view(deserializer));
    }
    return ans_;
  }

  @protected
  ModuleView sse_decode_module_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_code = sse_decode_String(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_language = sse_decode_String(deserializer);
    var var_verses = sse_decode_u_32(deserializer);
    return ModuleView(
      code: var_code,
      title: var_title,
      language: var_language,
      verses: var_verses,
    );
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParseOutcome sse_decode_parse_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_osis = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    return ParseOutcome(osis: var_osis, error: var_error);
  }

  @protected
  RunView sse_decode_run_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_x = sse_decode_f_64(deserializer);
    var var_width = sse_decode_f_64(deserializer);
    var var_verseNumber = sse_decode_bool(deserializer);
    return RunView(
      text: var_text,
      x: var_x,
      width: var_width,
      verseNumber: var_verseNumber,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  VerseView sse_decode_verse_view(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_verse = sse_decode_u_16(deserializer);
    var var_text = sse_decode_String(deserializer);
    return VerseView(verse: var_verse, text: var_text);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_chapter_layout_view(
    ChapterLayoutView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_line_view(self.lines, serializer);
    sse_encode_u_16(self.unitsPerEm, serializer);
    sse_encode_i_64(self.measureUnits, serializer);
    sse_encode_f_64(self.numberScale, serializer);
    sse_encode_String(self.plainText, serializer);
  }

  @protected
  void sse_encode_chapter_ref_view(
    ChapterRefView self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.bookOsis, serializer);
    sse_encode_u_16(self.chapter, serializer);
    sse_encode_String(self.heading, serializer);
    sse_encode_i_64(self.textLength, serializer);
  }

  @protected
  void sse_encode_chapter_view(ChapterView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.osis, serializer);
    sse_encode_list_verse_view(self.verses, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_line_view(LineView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_run_view(self.runs, serializer);
  }

  @protected
  void sse_encode_list_chapter_ref_view(
    List<ChapterRefView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_chapter_ref_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_line_view(
    List<LineView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_line_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_module_view(
    List<ModuleView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_module_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_32_strict(
    Uint32List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint32List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_run_view(List<RunView> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_run_view(item, serializer);
    }
  }

  @protected
  void sse_encode_list_verse_view(
    List<VerseView> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_verse_view(item, serializer);
    }
  }

  @protected
  void sse_encode_module_view(ModuleView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.code, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.language, serializer);
    sse_encode_u_32(self.verses, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_parse_outcome(ParseOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.osis, serializer);
    sse_encode_opt_String(self.error, serializer);
  }

  @protected
  void sse_encode_run_view(RunView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.width, serializer);
    sse_encode_bool(self.verseNumber, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_verse_view(VerseView self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.verse, serializer);
    sse_encode_String(self.text, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
