// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_library`

void openLibrary({required String path}) =>
    RustLib.instance.api.crateApiLibraryOpenLibrary(path: path);

Future<ModuleView> importOsisFile({required String path}) =>
    RustLib.instance.api.crateApiLibraryImportOsisFile(path: path);

List<ModuleView> modules() => RustLib.instance.api.crateApiLibraryModules();

List<ChapterRefView> contents({required String moduleCode}) =>
    RustLib.instance.api.crateApiLibraryContents(moduleCode: moduleCode);

/// Footnotes of one chapter, ordered by verse and sequence.
List<NoteView> chapterNotes({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
}) => RustLib.instance.api.crateApiLibraryChapterNotes(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
);

List<VerseView> chapterVerses({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
}) => RustLib.instance.api.crateApiLibraryChapterVerses(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
);

/// Resolve a reference and return the containing chapter of the given module.
ChapterView chapter({required String moduleCode, required String reference}) =>
    RustLib.instance.api.crateApiLibraryChapter(
      moduleCode: moduleCode,
      reference: reference,
    );

/// One entry of a module's chapter spine, with a heading localized to the
/// module's language (German book names for `de` modules, English otherwise).
class ChapterRefView {
  final String bookOsis;
  final int chapter;
  final String heading;

  /// Chapter text length in bytes, for scroll-height estimation.
  final PlatformInt64 textLength;

  const ChapterRefView({
    required this.bookOsis,
    required this.chapter,
    required this.heading,
    required this.textLength,
  });

  @override
  int get hashCode =>
      bookOsis.hashCode ^
      chapter.hashCode ^
      heading.hashCode ^
      textLength.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterRefView &&
          runtimeType == other.runtimeType &&
          bookOsis == other.bookOsis &&
          chapter == other.chapter &&
          heading == other.heading &&
          textLength == other.textLength;
}

class ChapterView {
  final String osis;
  final List<VerseView> verses;

  const ChapterView({required this.osis, required this.verses});

  @override
  int get hashCode => osis.hashCode ^ verses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterView &&
          runtimeType == other.runtimeType &&
          osis == other.osis &&
          verses == other.verses;
}

class ModuleView {
  final String code;
  final String title;
  final String language;
  final int verses;
  final int notes;

  const ModuleView({
    required this.code,
    required this.title,
    required this.language,
    required this.verses,
    required this.notes,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      title.hashCode ^
      language.hashCode ^
      verses.hashCode ^
      notes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleView &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          title == other.title &&
          language == other.language &&
          verses == other.verses &&
          notes == other.notes;
}

class NoteView {
  final int verse;
  final String text;

  const NoteView({required this.verse, required this.text});

  @override
  int get hashCode => verse.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteView &&
          runtimeType == other.runtimeType &&
          verse == other.verse &&
          text == other.text;
}

class VerseView {
  final int verse;
  final String text;

  const VerseView({required this.verse, required this.text});

  @override
  int get hashCode => verse.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerseView &&
          runtimeType == other.runtimeType &&
          verse == other.verse &&
          text == other.text;
}
