// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `display_key`, `with_library`

void openLibrary({required String path}) =>
    RustLib.instance.api.crateApiLibraryOpenLibrary(path: path);

Future<ModuleView> importOsisFile({required String path}) =>
    RustLib.instance.api.crateApiLibraryImportOsisFile(path: path);

/// Import a SWORD package (a CrossWire zip): zCom commentaries
/// (ADR 0017) and zLD dictionaries (ADR 0019), dispatched by driver.
Future<ModuleView> importSwordFile({required String path}) =>
    RustLib.instance.api.crateApiLibraryImportSwordFile(path: path);

/// Search a dictionary module: Strong numbers ("26", "G26"), headwords,
/// transliterations, and body text (Unicode case-insensitive).
List<DictHitView> dictSearch({
  required String moduleCode,
  required String query,
}) => RustLib.instance.api.crateApiLibraryDictSearch(
  moduleCode: moduleCode,
  query: query,
);

/// Every occurrence of a Strong number ("G26") in the first tagged
/// Bible module — the concordance.
ConcordanceResult concordanceOf({required String strong, required int limit}) =>
    RustLib.instance.api.crateApiLibraryConcordanceOf(
      strong: strong,
      limit: limit,
    );

/// The Strong number(s) a word in a verse is linked to (ADR 0020).
List<String> strongsFor({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
  required int verse,
  required String word,
}) => RustLib.instance.api.crateApiLibraryStrongsFor(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
  verse: verse,
  word: word,
);

/// Commentary entries of one chapter, ordered by starting verse.
List<CommentView> chapterComments({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
}) => RustLib.instance.api.crateApiLibraryChapterComments(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
);

List<ModuleView> modules() => RustLib.instance.api.crateApiLibraryModules();

List<ChapterRefView> contents({required String moduleCode}) =>
    RustLib.instance.api.crateApiLibraryContents(moduleCode: moduleCode);

/// Footnotes of one chapter, ordered by verse and sequence.
List<NoteView> chapterNotes({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
}) => RustLib.instance.api.crateApiLibraryChapterNotes(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
);

List<VerseView> chapterVerses({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
}) => RustLib.instance.api.crateApiLibraryChapterVerses(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
);

/// Resolve a reference and return the containing chapter of the given module.
ChapterView chapter({required String moduleCode, required String reference}) =>
    RustLib.instance.api.crateApiLibraryChapter(
      moduleCode: moduleCode,
      reference: reference,
    );

/// One entry of a module's chapter spine, with a heading localized to the
/// module's language (German book names for `de` modules, English otherwise).
class ChapterRefView {
  final String bookOsis;
  final int chapter;
  final String heading;

  /// Chapter text length in bytes, for scroll-height estimation.
  final PlatformInt64 textLength;

  /// Highest verse number in the chapter.
  final int maxVerse;

  /// Concise display abbreviation of the book.
  final String bookAbbrev;

  /// Traditional canon grouping (0..8), for the book-grid palette.
  final int bookCategory;

  const ChapterRefView({
    required this.bookOsis,
    required this.chapter,
    required this.heading,
    required this.textLength,
    required this.maxVerse,
    required this.bookAbbrev,
    required this.bookCategory,
  });

  @override
  int get hashCode =>
      bookOsis.hashCode ^
      chapter.hashCode ^
      heading.hashCode ^
      textLength.hashCode ^
      maxVerse.hashCode ^
      bookAbbrev.hashCode ^
      bookCategory.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterRefView &&
          runtimeType == other.runtimeType &&
          bookOsis == other.bookOsis &&
          chapter == other.chapter &&
          heading == other.heading &&
          textLength == other.textLength &&
          maxVerse == other.maxVerse &&
          bookAbbrev == other.bookAbbrev &&
          bookCategory == other.bookCategory;
}

class ChapterView {
  final String osis;
  final List<VerseView> verses;

  const ChapterView({required this.osis, required this.verses});

  @override
  int get hashCode => osis.hashCode ^ verses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterView &&
          runtimeType == other.runtimeType &&
          osis == other.osis &&
          verses == other.verses;
}

/// One commentary section (ADR 0017): a verse range of one chapter, with
/// paragraphs separated by "\n\n" and explicit references from the source.
class CommentView {
  final int verseStart;
  final int verseEnd;
  final String? heading;
  final String text;
  final List<NoteRefView> refs;

  const CommentView({
    required this.verseStart,
    required this.verseEnd,
    this.heading,
    required this.text,
    required this.refs,
  });

  @override
  int get hashCode =>
      verseStart.hashCode ^
      verseEnd.hashCode ^
      heading.hashCode ^
      text.hashCode ^
      refs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentView &&
          runtimeType == other.runtimeType &&
          verseStart == other.verseStart &&
          verseEnd == other.verseEnd &&
          heading == other.heading &&
          text == other.text &&
          refs == other.refs;
}

class ConcordanceResult {
  /// The Strong's-tagged module the occurrences come from, if any is
  /// installed.
  final String? module;
  final List<OccurrenceView> hits;

  const ConcordanceResult({this.module, required this.hits});

  @override
  int get hashCode => module.hashCode ^ hits.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConcordanceResult &&
          runtimeType == other.runtimeType &&
          module == other.module &&
          hits == other.hits;
}

/// A dictionary search hit (ADR 0019), ranked headword-first.
class DictHitView {
  final int sort;

  /// User-facing key ("G26" for Strong's Greek).
  final String displayKey;
  final String headword;
  final String pron;

  const DictHitView({
    required this.sort,
    required this.displayKey,
    required this.headword,
    required this.pron,
  });

  @override
  int get hashCode =>
      sort.hashCode ^ displayKey.hashCode ^ headword.hashCode ^ pron.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictHitView &&
          runtimeType == other.runtimeType &&
          sort == other.sort &&
          displayKey == other.displayKey &&
          headword == other.headword &&
          pron == other.pron;
}

class ModuleView {
  final String code;
  final String title;
  final String language;

  /// Content units: verses of a Bible text, entries of a commentary.
  final int verses;
  final int notes;

  /// "bible" or "commentary" (ADR 0017).
  final String kind;

  const ModuleView({
    required this.code,
    required this.title,
    required this.language,
    required this.verses,
    required this.notes,
    required this.kind,
  });

  @override
  int get hashCode =>
      code.hashCode ^
      title.hashCode ^
      language.hashCode ^
      verses.hashCode ^
      notes.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ModuleView &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          title == other.title &&
          language == other.language &&
          verses == other.verses &&
          notes == other.notes &&
          kind == other.kind;
}

class NoteRefView {
  final int start;
  final int end;

  /// Canonical OSIS form of the found reference.
  final String osis;

  const NoteRefView({
    required this.start,
    required this.end,
    required this.osis,
  });

  @override
  int get hashCode => start.hashCode ^ end.hashCode ^ osis.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteRefView &&
          runtimeType == other.runtimeType &&
          start == other.start &&
          end == other.end &&
          osis == other.osis;
}

class NoteView {
  final int verse;

  /// Marker letter matching the inline marker in the text ("a", "b", …).
  final String label;
  final String text;

  /// Verse references found inside the note text, as byte ranges.
  final List<NoteRefView> refs;

  const NoteView({
    required this.verse,
    required this.label,
    required this.text,
    required this.refs,
  });

  @override
  int get hashCode =>
      verse.hashCode ^ label.hashCode ^ text.hashCode ^ refs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteView &&
          runtimeType == other.runtimeType &&
          verse == other.verse &&
          label == other.label &&
          text == other.text &&
          refs == other.refs;
}

/// One concordance occurrence (ADR 0020): a verse whose byte range
/// [start, end) is covered by the Strong number searched.
class OccurrenceView {
  final String bookOsis;
  final int chapter;
  final int verse;
  final int start;
  final int end;
  final String text;

  const OccurrenceView({
    required this.bookOsis,
    required this.chapter,
    required this.verse,
    required this.start,
    required this.end,
    required this.text,
  });

  @override
  int get hashCode =>
      bookOsis.hashCode ^
      chapter.hashCode ^
      verse.hashCode ^
      start.hashCode ^
      end.hashCode ^
      text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is OccurrenceView &&
          runtimeType == other.runtimeType &&
          bookOsis == other.bookOsis &&
          chapter == other.chapter &&
          verse == other.verse &&
          start == other.start &&
          end == other.end &&
          text == other.text;
}

class VerseView {
  final int verse;
  final String text;

  const VerseView({required this.verse, required this.text});

  @override
  int get hashCode => verse.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerseView &&
          runtimeType == other.runtimeType &&
          verse == other.verse &&
          text == other.text;
}
