// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

ParseOutcome parseReference({required String input}) =>
    RustLib.instance.api.crateApiReferencesParseReference(input: input);

/// Concise display form of a canonical OSIS reference ("1Mo 3,1"); falls
/// back to the input when it does not parse.
String formatReference({required String osis}) =>
    RustLib.instance.api.crateApiReferencesFormatReference(osis: osis);

/// Outcome of parsing user input as a Bible reference: exactly one of the two
/// fields is set.
class ParseOutcome {
  final String? osis;
  final String? error;

  const ParseOutcome({this.osis, this.error});

  @override
  int get hashCode => osis.hashCode ^ error.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseOutcome &&
          runtimeType == other.runtimeType &&
          osis == other.osis &&
          error == other.error;
}
