// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void initTypesetting({required List<int> fontData}) =>
    RustLib.instance.api.crateApiTypesetInitTypesetting(fontData: fontData);

/// Async on purpose: runs on a worker thread so scrolling never blocks on
/// shaping and breaking.
Future<ChapterLayoutView> layoutChapter({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
}) => RustLib.instance.api.crateApiTypesetLayoutChapter(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
);

/// Text-line count of every chapter in the module's spine order, at the
/// canonical measure. This makes global line numbering possible, which the
/// multi-column reader chunks into viewport-sized columns — layout itself
/// never depends on the viewport.
Future<Uint32List> moduleLineCounts({required String moduleCode}) => RustLib
    .instance
    .api
    .crateApiTypesetModuleLineCounts(moduleCode: moduleCode);

class ChapterLayoutView {
  final List<LineView> lines;
  final int unitsPerEm;

  /// Line width in font units (MEASURE_EMS ems).
  final PlatformInt64 measureUnits;

  /// Verse numbers render at this fraction of the text size.
  final double numberScale;

  /// Flowing text of the chapter, for accessibility semantics.
  final String plainText;

  const ChapterLayoutView({
    required this.lines,
    required this.unitsPerEm,
    required this.measureUnits,
    required this.numberScale,
    required this.plainText,
  });

  @override
  int get hashCode =>
      lines.hashCode ^
      unitsPerEm.hashCode ^
      measureUnits.hashCode ^
      numberScale.hashCode ^
      plainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterLayoutView &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          unitsPerEm == other.unitsPerEm &&
          measureUnits == other.measureUnits &&
          numberScale == other.numberScale &&
          plainText == other.plainText;
}

class LineView {
  final List<RunView> runs;

  const LineView({required this.runs});

  @override
  int get hashCode => runs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineView &&
          runtimeType == other.runtimeType &&
          runs == other.runs;
}

class RunView {
  final String text;

  /// Left edge in font units.
  final double x;

  /// Shaped width in font units.
  final double width;
  final bool verseNumber;

  const RunView({
    required this.text,
    required this.x,
    required this.width,
    required this.verseNumber,
  });

  @override
  int get hashCode =>
      text.hashCode ^ x.hashCode ^ width.hashCode ^ verseNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          x == other.x &&
          width == other.width &&
          verseNumber == other.verseNumber;
}
