// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `activate_font`, `active_measure`, `entry_layout`, `prose_paragraphs`, `view_lines`

void initTypesetting({required List<int> fontData}) =>
    RustLib.instance.api.crateApiTypesetInitTypesetting(fontData: fontData);

/// Switch the typesetting face (the user's typeface setting): every
/// later layout uses the new metrics, so callers re-measure and re-lay
/// their modules just as after a measure change.
void setTypesetFont({required List<int> fontData}) =>
    RustLib.instance.api.crateApiTypesetSetTypesetFont(fontData: fontData);

/// Async on purpose: runs on a worker thread so scrolling never blocks on
/// shaping and breaking.
Future<ChapterLayoutView> layoutChapter({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
  required int measureEms,
}) => RustLib.instance.api.crateApiTypesetLayoutChapter(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
  measureEms: measureEms,
);

/// Typeset the commentary sections of one chapter at `measure_ems` ems —
/// the pane's width in ems of its text size; commentary reflows freely,
/// without the reader's protected measure. Async: shaping and breaking
/// run on a worker thread.
Future<List<CommentLayoutView>> layoutComments({
  required String moduleCode,
  required String bookOsis,
  required int chapter,
  required double measureEms,
}) => RustLib.instance.api.crateApiTypesetLayoutComments(
  moduleCode: moduleCode,
  bookOsis: bookOsis,
  chapter: chapter,
  measureEms: measureEms,
);

/// Typeset one dictionary entry at `measure_ems` ems of its text size.
/// Async: shaping and breaking run on a worker thread.
Future<DictLayoutView?> layoutDictEntry({
  required String moduleCode,
  required int sort,
  required double measureEms,
}) => RustLib.instance.api.crateApiTypesetLayoutDictEntry(
  moduleCode: moduleCode,
  sort: sort,
  measureEms: measureEms,
);

/// Typeset a devotional day's readings (ADR 0021): every section whose
/// sort lies in the day's range, in order. Async.
Future<List<DictLayoutView>> layoutDevotionalDay({
  required String moduleCode,
  required int month,
  required int day,
  required double measureEms,
}) => RustLib.instance.api.crateApiTypesetLayoutDevotionalDay(
  moduleCode: moduleCode,
  month: month,
  day: day,
  measureEms: measureEms,
);

/// Typeset one section of a general book at `measure_ems` ems. Async.
Future<BookLayoutView?> layoutBookSection({
  required String moduleCode,
  required int ordinal,
  required double measureEms,
}) => RustLib.instance.api.crateApiTypesetLayoutBookSection(
  moduleCode: moduleCode,
  ordinal: ordinal,
  measureEms: measureEms,
);

/// Text-line count of every chapter in the module's spine order, at the
/// canonical measure. This makes global line numbering possible, which the
/// multi-column reader chunks into viewport-sized columns — layout itself
/// never depends on the viewport.
/// Per chapter, one byte per laid-out line: 0 = content, 1 = heading,
/// 2 = blank. Line counts are the row lengths; the kinds feed the
/// column plan's heading keep-with-next rule (ADR 0026).
Future<List<Uint8List>> moduleLineKinds({
  required String moduleCode,
  required int measureEms,
}) => RustLib.instance.api.crateApiTypesetModuleLineKinds(
  moduleCode: moduleCode,
  measureEms: measureEms,
);

/// One book section, typeset (ADR 0021).
class BookLayoutView {
  final int ordinal;
  final int level;
  final String name;
  final List<LineView> lines;

  /// OSIS targets by `RunView.link` index.
  final List<String> refs;
  final int? prevOrdinal;
  final int? nextOrdinal;
  final int unitsPerEm;
  final PlatformInt64 measureUnits;
  final double numberScale;
  final String plainText;

  const BookLayoutView({
    required this.ordinal,
    required this.level,
    required this.name,
    required this.lines,
    required this.refs,
    this.prevOrdinal,
    this.nextOrdinal,
    required this.unitsPerEm,
    required this.measureUnits,
    required this.numberScale,
    required this.plainText,
  });

  @override
  int get hashCode =>
      ordinal.hashCode ^
      level.hashCode ^
      name.hashCode ^
      lines.hashCode ^
      refs.hashCode ^
      prevOrdinal.hashCode ^
      nextOrdinal.hashCode ^
      unitsPerEm.hashCode ^
      measureUnits.hashCode ^
      numberScale.hashCode ^
      plainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BookLayoutView &&
          runtimeType == other.runtimeType &&
          ordinal == other.ordinal &&
          level == other.level &&
          name == other.name &&
          lines == other.lines &&
          refs == other.refs &&
          prevOrdinal == other.prevOrdinal &&
          nextOrdinal == other.nextOrdinal &&
          unitsPerEm == other.unitsPerEm &&
          measureUnits == other.measureUnits &&
          numberScale == other.numberScale &&
          plainText == other.plainText;
}

class ChapterLayoutView {
  final List<LineView> lines;
  final int unitsPerEm;

  /// Line width in font units (MEASURE_EMS ems).
  final PlatformInt64 measureUnits;

  /// Verse numbers render at this fraction of the text size.
  final double numberScale;

  /// Flowing text of the chapter, for accessibility semantics.
  final String plainText;

  const ChapterLayoutView({
    required this.lines,
    required this.unitsPerEm,
    required this.measureUnits,
    required this.numberScale,
    required this.plainText,
  });

  @override
  int get hashCode =>
      lines.hashCode ^
      unitsPerEm.hashCode ^
      measureUnits.hashCode ^
      numberScale.hashCode ^
      plainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChapterLayoutView &&
          runtimeType == other.runtimeType &&
          lines == other.lines &&
          unitsPerEm == other.unitsPerEm &&
          measureUnits == other.measureUnits &&
          numberScale == other.numberScale &&
          plainText == other.plainText;
}

/// One commentary section, typeset (ADR 0018): the same engine as the
/// Bible text, at the pane's own measure. Runs with a `link` index are
/// tappable references resolving through `refs`.
class CommentLayoutView {
  final int verseStart;
  final int verseEnd;
  final List<LineView> lines;

  /// OSIS targets by `RunView.link` index.
  final List<String> refs;
  final int unitsPerEm;

  /// Line width in font units for this layout.
  final PlatformInt64 measureUnits;

  /// The label renders at this fraction of the text size.
  final double numberScale;

  /// Flowing text of the entry, for accessibility semantics.
  final String plainText;

  const CommentLayoutView({
    required this.verseStart,
    required this.verseEnd,
    required this.lines,
    required this.refs,
    required this.unitsPerEm,
    required this.measureUnits,
    required this.numberScale,
    required this.plainText,
  });

  @override
  int get hashCode =>
      verseStart.hashCode ^
      verseEnd.hashCode ^
      lines.hashCode ^
      refs.hashCode ^
      unitsPerEm.hashCode ^
      measureUnits.hashCode ^
      numberScale.hashCode ^
      plainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CommentLayoutView &&
          runtimeType == other.runtimeType &&
          verseStart == other.verseStart &&
          verseEnd == other.verseEnd &&
          lines == other.lines &&
          refs == other.refs &&
          unitsPerEm == other.unitsPerEm &&
          measureUnits == other.measureUnits &&
          numberScale == other.numberScale &&
          plainText == other.plainText;
}

/// One dictionary entry, typeset (ADR 0019): key label, headword line,
/// and the body through the same engine as everything else. Verse
/// references found in the prose are tappable link runs.
class DictLayoutView {
  final int sort;
  final String displayKey;
  final String headword;
  final String pron;
  final List<LineView> lines;

  /// OSIS targets by `RunView.link` index.
  final List<String> refs;
  final int? prevSort;
  final int? nextSort;
  final int unitsPerEm;
  final PlatformInt64 measureUnits;
  final double numberScale;
  final String plainText;

  const DictLayoutView({
    required this.sort,
    required this.displayKey,
    required this.headword,
    required this.pron,
    required this.lines,
    required this.refs,
    this.prevSort,
    this.nextSort,
    required this.unitsPerEm,
    required this.measureUnits,
    required this.numberScale,
    required this.plainText,
  });

  @override
  int get hashCode =>
      sort.hashCode ^
      displayKey.hashCode ^
      headword.hashCode ^
      pron.hashCode ^
      lines.hashCode ^
      refs.hashCode ^
      prevSort.hashCode ^
      nextSort.hashCode ^
      unitsPerEm.hashCode ^
      measureUnits.hashCode ^
      numberScale.hashCode ^
      plainText.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DictLayoutView &&
          runtimeType == other.runtimeType &&
          sort == other.sort &&
          displayKey == other.displayKey &&
          headword == other.headword &&
          pron == other.pron &&
          lines == other.lines &&
          refs == other.refs &&
          prevSort == other.prevSort &&
          nextSort == other.nextSort &&
          unitsPerEm == other.unitsPerEm &&
          measureUnits == other.measureUnits &&
          numberScale == other.numberScale &&
          plainText == other.plainText;
}

class LineView {
  final List<RunView> runs;

  const LineView({required this.runs});

  @override
  int get hashCode => runs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LineView &&
          runtimeType == other.runtimeType &&
          runs == other.runs;
}

class RunView {
  final String text;

  /// Left edge in font units.
  final double x;

  /// Shaped width in font units.
  final double width;
  final bool verseNumber;

  /// An inline lettered footnote marker.
  final bool noteMarker;

  /// Section heading level (0 = body, 1 = section, 2 = subsection).
  final int headingLevel;

  /// The verse this run belongs to.
  final int verse;

  /// Reference index in the owning layout's refs (prose, ADR 0018);
  /// tapping the run opens that reference. None for plain text.
  final int? link;

  /// Byte offset of the run within its verse's text (ADR 0023);
  /// zero for non-word runs and prose layouts.
  final int offset;

  const RunView({
    required this.text,
    required this.x,
    required this.width,
    required this.verseNumber,
    required this.noteMarker,
    required this.headingLevel,
    required this.verse,
    this.link,
    required this.offset,
  });

  @override
  int get hashCode =>
      text.hashCode ^
      x.hashCode ^
      width.hashCode ^
      verseNumber.hashCode ^
      noteMarker.hashCode ^
      headingLevel.hashCode ^
      verse.hashCode ^
      link.hashCode ^
      offset.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RunView &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          x == other.x &&
          width == other.width &&
          verseNumber == other.verseNumber &&
          noteMarker == other.noteMarker &&
          headingLevel == other.headingLevel &&
          verse == other.verse &&
          link == other.link &&
          offset == other.offset;
}
