// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void openUserStore({required String path}) =>
    RustLib.instance.api.crateApiUserOpenUserStore(path: path);

/// Persist the layout object (ADR 0008): the serialized description of the
/// current view arrangement.
void saveLayout({required String json}) =>
    RustLib.instance.api.crateApiUserSaveLayout(json: json);

String? loadLayout() => RustLib.instance.api.crateApiUserLoadLayout();
