// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `with_store`

void openUserStore({required String path}) =>
    RustLib.instance.api.crateApiUserOpenUserStore(path: path);

/// Persist one synced user value (desks, layout objects, later notes);
/// the write is stamped and appended to the sync op-log (ADR 0014).
void userSet({required String key, required String value}) =>
    RustLib.instance.api.crateApiUserUserSet(key: key, value: value);

String? userGet({required String key}) =>
    RustLib.instance.api.crateApiUserUserGet(key: key);

/// Point the store at a synced folder (None disables sync). Fails when
/// the folder cannot be written.
void configureSync({String? dir}) =>
    RustLib.instance.api.crateApiUserConfigureSync(dir: dir);

String? syncDir() => RustLib.instance.api.crateApiUserSyncDir();

/// Pull changes other installations wrote into the sync folder; returns
/// the changed keys so the UI can react.
List<String> syncNow() => RustLib.instance.api.crateApiUserSyncNow();
